services:
  postgres:
    image: postgres
    container_name: postgres_kahala
    ports:
      - 5440:5432
    env_file:
      - ./db/app.env
#    volumes:
#      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
